# Generated by Django 4.2.23 on 2025-09-08 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Samochod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255)),
                ('opis', models.TextField()),
                ('kategoria', models.CharField(choices=[('motocykl', 'Motocykl'), ('osobowy', 'Osobowy'), ('ciezarowy', 'Ciężarowy')], max_length=20)),
                ('marka', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('rok_produkcji', models.PositiveIntegerField()),
                ('przebieg', models.PositiveIntegerField(help_text='W kilometrach')),
                ('pojemnosc_skokowa', models.PositiveIntegerField(help_text='W cm³')),
                ('moc', models.PositiveIntegerField(help_text='W KM')),
                ('rodzaj_paliwa', models.CharField(choices=[('benzyna', 'Benzyna'), ('diesel', 'Diesel'), ('lpg', 'LPG')], max_length=10)),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='pojazdy/')),
                ('data_dodania', models.DateField(auto_now_add=True)),
                ('data_publikacji', models.DateField(blank=True, null=True)),
                ('usunieta', models.BooleanField(default=False)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
