# Generated by Django 4.2.23 on 2025-09-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSellApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazd',
            name='czy_opublikowany',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pojazd',
            name='czy_usuniety',
            field=models.BooleanField(default=False),
        ),
    ]
